package com.example.taskmaster.domain;

import lombok.Builder;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * Spring Data JDBC entity representing a row in the {@code tasks} table.
 *
 * <p>Intentionally a plain record — no JPA, no lazy loading, no session.
 * All fields map directly to database columns by name (snake_case ↔ camelCase
 * via {@link Column} where needed).
 */
@Builder(toBuilder = true)
@Table("tasks")
public record Task(

        /**
         * Globally unique task identifier. Generated by PostgreSQL ({@code gen_random_uuid()})
         * on insert; never supplied by the caller.
         */
        @Id
        UUID id,

        /**
         * Logical queue this task belongs to (e.g. {@code "email-queue"}).
         * Workers register against a specific queue and only claim tasks from it.
         */
        @Column("queue_name")
        String queueName,

        /**
         * Arbitrary JSON payload supplied by the submitter. Taskmaster treats this
         * as opaque bytes — it is passed through to the worker unchanged.
         * Stored as {@code JSONB} in PostgreSQL for efficient indexing if needed.
         */
        String payload,

        /**
         * Scheduling priority. Higher values are claimed first.
         * Tasks with the same priority are ordered by {@code created_at} (FIFO).
         * Defaults to {@code 0}; submitters may pass negative values to deprioritise.
         */
        int priority,

        /**
         * Current lifecycle state of the task as a VARCHAR.
         * One of: {@code PENDING}, {@code RUNNING}, {@code DONE}, {@code DEAD}.
         * See {@link TaskStatus} for the full state machine.
         */
        String status,

        /**
         * ID of the worker currently processing this task ({@code tasks.worker_id → workers.id}).
         * {@code null} when the task is not in {@code RUNNING} state.
         */
        @Column("worker_id")
        String workerId,

        /**
         * Total number of execution attempts consumed so far, including the current one.
         * Incremented atomically during the claim query. Used to decide whether to
         * retry or move the task to {@code DEAD} on failure.
         */
        int attempts,

        /**
         * Maximum number of attempts allowed before the task is marked {@code DEAD}.
         * Supplied by the submitter; defaults to {@code 3}.
         */
        @Column("max_attempts")
        int maxAttempts,

        /**
         * Wall-clock time when the task was first submitted (set by the database default).
         * Used for FIFO ordering within the same priority level.
         */
        @Column("created_at")
        Instant createdAt,

        /**
         * Wall-clock time when the task was most recently claimed by a worker.
         * Reset to {@code null} when a task is requeued after worker death.
         * Used by observability tooling to detect long-running tasks.
         */
        @Column("claimed_at")
        Instant claimedAt,

        /**
         * Wall-clock time when the task reached a terminal state ({@code DONE} or {@code DEAD}).
         * {@code null} while the task is still in progress or pending.
         */
        @Column("finished_at")
        Instant finishedAt,

        /**
         * Earliest time at which this task is eligible to be claimed again after a failure.
         * {@code null} means the task is immediately eligible (no backoff).
         * Computed as {@code now() + 2^attempts × 5 seconds}, capped at 5 minutes.
         */
        @Column("next_attempt_at")
        Instant nextAttemptAt,

        /**
         * Opaque result string set by the worker on successful completion
         * (e.g. {@code "sent:msg-id-123"}). {@code null} unless status is {@code DONE}.
         */
        String result,

        /**
         * Error message from the most recent failed attempt.
         * Preserved across retries so the final {@code DEAD} record retains the last error.
         */
        @Column("last_error")
        String lastError,

        /**
         * Optional hard deadline for task execution. If the task is still PENDING after
         * this timestamp the {@code DeadlineReaper} will move it directly to DEAD.
         * {@code null} means no deadline — the task remains eligible indefinitely.
         */
        Instant deadline,

        /**
         * Required capability tags for this task. A worker can only claim this task
         * if its capability set is a superset of these tags. Empty means any worker
         * on the queue can claim it.
         */
        Tags tags,

        /**
         * Optional callback URL for webhook delivery. When set, Taskmaster will POST
         * task results to this URL when the task reaches a terminal state (DONE or DEAD).
         */
        @Column("callback_url")
        String callbackUrl

) {
    public Task {
        if (tags == null) tags = Tags.EMPTY;
    }
}
